---
- name: PiholeInstall
  hosts: pihole
  gather_facts: yes
  user: przemek
  become: yes
  become_user: root
  collections:
    - oracle.oci

  vars:
    ansible_host_key_checking: false

  pre_tasks:
  - name: Check connectivity
    ping:

  tasks:
  - name: Set timezone to Europe/Warsaw
    shell: timedatectl set-timezone "Europe/Warsaw"

  - name: Update system
    apt:
      name: "*"
      state: latest
      update_cache: yes
      autoremove: yes
