---
- name: PiholeInstall
  hosts: pihole
  gather_facts: yes
  user: przemek
  become: yes
  become_user: root
  collections:
    - community.general.parted
    - community.general.filesystem

  vars:
    os_environment:
      - key: PIHOLE_ADMIN_PASS
        value: "{{ lookup('env', 'PIHOLE_ADMIN_PASS' )}}"
      - key: DYNU_API_KEY
        value: "{{ lookup('env', 'DYNU_API_KEY' )}}"

  pre_tasks:
  - name: Check connectivity
    ping:

  - name: Customize /etc/environment
    ansible.builtin.lineinfile:
      dest: "/etc/environment"
      state: present
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
    with_items: "{{ os_environment }}"
    no_log: true

  tasks:
  - name: Set timezone to Europe/Warsaw
    shell: timedatectl set-timezone "Europe/Warsaw"

  - name: Update system
    apt:
      name: "*"
      state: latest
      update_cache: yes
      autoremove: yes

  - name: Create mounting directories 
    file:
      state: directory
      path: "{{ item }}"
      owner: root
      group: root
      mode: '0777'
    with_items:
      - "/pihole"
      - "/pihole/data"
      - "/pihole/etc-dnsmasq.d"

  - name: Create a new partition on /dev/sdb
    community.general.parted:
      device: /dev/sdb
      number: 1
      state: present

  - filesystem:
      fstype: xfs
      dev: /dev/sdb1
    register: filesystem_data

  - name: Mount block storage
    mount:
      path: /pihole
      src: "/dev/sdb1"
      state: present
      fstype: xfs
      opts: defaults,nofail

  - name: Refrest mount drives
    shell: mount -a

  - name: Copy docker-compose file
    template:
      src: docker-compose.j2
      dest: /pihole/docker-compose.yml
      owner: root
      group: root
      mode: '0660'
