---
- name: PiholeInstall
  hosts: pihole
  gather_facts: yes
  user: przemek
  become: yes
  become_user: root
  collections:
    - community.general.parted
    - community.general.filesystem
    - community.docker

  vars_files:
  -  ./vault.yml

  vars:
  - pihole_image: pihole/pihole:latest
  - trafeik_image: traefik:latest
  - pihole_directory: /pihole
  - traefik_directory: /traefik
  - domain: pgorzynski.freeddns.org
  - next_dns_server: "45.90.28.197"


  pre_tasks:
  - name: Check connectivity
    ping:

  - name: Customize /etc/environment
    ansible.builtin.lineinfile:
      dest: "/etc/environment"
      state: present
      line: "DYNU_API_KEY={{ DYNU_API_KEY }}"
    no_log: true

  tasks:
  - name: Set timezone to Europe/Warsaw
    shell: timedatectl set-timezone "Europe/Warsaw"

  - name: Update system
    apt:
      name: "*"
      state: latest
      update_cache: yes
      autoremove: yes

  - name: Create mounting directories 
    file:
      state: directory
      path: "{{ item }}"
      owner: root
      group: root
      mode: '0777'
    with_items:
      - "{{ pihole_directory }}"
      - "{{ pihole_directory }}/data"
      - "{{ pihole_directory }}/etc-dnsmasq.d"
      - "{{ traefik_directory }}/config"
      - "{{ traefik_directory }}/sslcerts"

  - name: Create a new partition on /dev/sdb
    community.general.parted:
      device: /dev/sdb
      number: 1
      state: present

  - filesystem:
      fstype: xfs
      dev: /dev/sdb1
    register: filesystem_data

  - name: Mount block storage
    mount:
      path: /pihole
      src: "/dev/sdb1"
      state: present
      fstype: xfs
      opts: defaults,nofail

  - name: Refrest mount drives
    shell: mount -a

  - name: Copy docker-compose file
    template:
      src: docker-compose.j2
      dest: /pihole/docker-compose.yml
      owner: root
      group: root
      mode: '0660'

  - name: Pull docker images
    shell: |
      docker pull "{{ item }}"
    with_items:
      - "{{ pihole_image }}"
      - "{{ trafeik_image }}"

  - name: Copy Traefik configuration
    ansible.builtin.copy:
      src: traefik.yml
      dest: "{{ traefik_directory }}/config/traefik.yml"
      owner: root
      group: root
      mode: '0644'

  - name: Stop and disable systemd-resolved
    ansible.builtin.service:
      name: systemd-resolved
      state: stopped
      enabled: false

  - name: Set Custom DNS
    shell: |
      echo "nameserver {{ next_dns_server }}" > /etc/resolv.conf

  - name: Run docker-compose
    shell: |
      cd /pihole && docker-compose up -d